services:

    pierrre_automatic_validator.orm_listener:
        class: Pierrre\AutomaticValidatorBundle\EventListener\ORMListener
        arguments: ["@pierrre_automatic_validator.automatic_validator"]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }